FROM ghcr.io/astral-sh/uv:python3.12-bookworm

RUN adduser petscagent
USER petscagent
WORKDIR /home/petscagent/petscagent_bench

COPY pyproject.toml ./
COPY README.md ./
COPY src src

RUN \
    --mount=type=cache,target=/home/petscagent/.cache/uv,uid=1000 \
    uv sync

ENTRYPOINT ["uv", "run", "src/client_cli.py"]
